# Generated by Django 2.0.5 on 2018-05-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('account_id', 'product_id', 'substitute_id')},
        ),
    ]
