#! /usr/bin/env python3
# coding: utf-8

PRODUCTS = [
    {
        "id": 1,
        "name": "Bâtons gouda",
        "brands": "Delacre",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-e.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/871/041/200/2340/front_fr.5.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/871/041/200/2340/front_fr.5.400.jpg",
        'sugars': 'high',
        'salt': 'high',
        'saturated_fat': 'high',
        'fat': 'high',
        "fat_100g": 29.8,
        "saturated_fat_100g": 15.6,
        "sugars_100g": 24.4,
        "salt_100g": 1.74,
        "link_off": "https://fr.openfoodfacts.org/produit/8710412002340/batons-gouda-delacre"
    }, {
        "id": 2,
        "name": "Matzen",
        "brands": "Paul Heumann",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-a.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/322/698/005/2502/front_de.5.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/322/698/005/2502/front_de.5.400.jpg",
        'sugars': 'low',
        'salt': 'low',
        'saturated_fat': 'low',
        'fat': 'low',
        "fat_100g": 1.2,
        "saturated_fat_100g": 0.3,
        "sugars_100g": 2.7,
        "salt_100g": 0.01,
        "link_off": "https://fr.openfoodfacts.org/produit/3226980052502/matzen-paul-heumann"
    }, {
        "id": 3,
        "name": "Pain Azyme",
        "brands": "Hollandia",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-a.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/871/053/610/0014/front_en.10.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/871/053/610/0014/front_en.10.400.jpg",
        'sugars': 'low',
        'salt': 'low',
        'saturated_fat': 'low',
        'fat': 'low',
        "fat_100g": 1,
        "saturated_fat_100g": 0,
        "sugars_100g": 0.4,
        "salt_100g": 0.005,
        "link_off": "https://fr.openfoodfacts.org/produit/8710536100014/pain-azyme-hollandia"
    }, {
        "id": 4,
        "name": "Smelties Maisflips",
        "brands": "Rej",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-a.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/859/403/891/4498/front_fr.4.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/859/403/891/4498/front_fr.4.400.jpg",
        'salt': 'low',
        'sugars': 'low',
        'saturated_fat': 'low',
        'fat': 'low',
        "fat_100g": 2.4,
        "saturated_fat_100g": 0,
        "sugars_100g": 0,
        "salt_100g": 0,
        "link_off": "https://fr.openfoodfacts.org/produit/8594038914498/smelties-maisflips-rej"
    }, {
        "id": 5,
        "name": "Mini flûte fromage",
        "brands": "U Bio, U",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-b.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/325/622/619/2938/front_fr.22.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/325/622/619/2938/front_fr.22.400.jpg",
        'fat': 'low',
        'saturated_fat': 'low',
        'sugars': 'low',
        'salt': 'moderate',
        "fat_100g": 0.4,
        "saturated_fat_100g": 0.1,
        "sugars_100g": 0.2,
        "salt_100g": 0.78,
        "link_off": "https://fr.openfoodfacts.org/produit/3256226192938/mini-flute-fromage-u-bio"
    }, {
        "id": 6,
        "name": "Craquelins au son d'avoine sésame lin & cumin",
        "brands": "Monoprix",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-c.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/335/003/321/0080/front_fr.10.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/335/003/321/0080/front_fr.10.400.jpg",
        'sugars': 'low',
        'salt': 'high',
        'saturated_fat': 'moderate',
        'fat': 'moderate',
        "fat_100g": 17,
        "saturated_fat_100g": 2.2,
        "sugars_100g": 4.6,
        "salt_100g": 1.6,
        "link_off": "https://fr.openfoodfacts.org/produit/3350033210080/craquelins-au-son-d-avoine-sesame-lin-cumin-monoprix"
    }, {
        "id": 7,
        "name": "Sticks &bretzels d alsace",
        "brands": "Ancel,Dr. Oetker",
        "nutriscore": "/static/product/img/nutrition_grades/nutriscore-d.png",
        "img_url_min": "https://static.openfoodfacts.org/images/products/302/703/000/8797/front_fr.19.200.jpg",
        "img_url_big": "https://static.openfoodfacts.org/images/products/302/703/000/8797/front_fr.19.400.jpg",
        'fat': 'moderate',
        'saturated_fat': 'low',
        'sugars': 'low',
        'salt': 'high',
        "fat_100g": 4.11,
        "saturated_fat_100g": 0.4,
        "sugars_100g": 1.9,
        "salt_100g": 4.3,
        "link_off": "https://fr.openfoodfacts.org/produit/3027030008797/sticks-bretzels-d-alsace-ancel"
    }
]