# Generated by Django 2.0.5 on 2018-05-21 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20180521_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='UserProfile',
        ),
    ]
