# Generated by Django 2.0.5 on 2018-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('product_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('brands', models.CharField(db_index=True, max_length=255, null=True)),
                ('categories', models.CharField(db_index=True, max_length=255, null=True)),
                ('nutrition_grades', models.CharField(db_index=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('image_small_url', models.CharField(max_length=255, null=True)),
                ('fat', models.CharField(max_length=255, null=True)),
                ('salt', models.CharField(max_length=255, null=True)),
                ('saturated_fat', models.CharField(max_length=255, null=True)),
                ('sugars', models.CharField(max_length=255, null=True)),
                ('fat_100g', models.IntegerField(null=True)),
                ('saturated_fat_100g', models.IntegerField(null=True)),
                ('sugars_100g', models.IntegerField(null=True)),
                ('salt_100g', models.IntegerField(null=True)),
            ],
        ),
    ]
