# Generated by Django 2.0.5 on 2018-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, null=True)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('brands', models.CharField(max_length=150, null=True)),
                ('categories', models.CharField(max_length=150, null=True)),
                ('nutrition_grade_uk', models.CharField(max_length=150, null=True)),
                ('image_url', models.CharField(max_length=150, null=True)),
                ('image_small_url', models.CharField(max_length=150, null=True)),
                ('url', models.CharField(max_length=150, null=True)),
                ('fat_100g', models.CharField(max_length=150, null=True)),
                ('saturated_fat_100g', models.CharField(max_length=150, null=True)),
                ('sugars_100g', models.CharField(max_length=150, null=True)),
                ('salt_100g', models.CharField(max_length=150, null=True)),
                ('serving_size', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
