# Generated by Django 2.0.5 on 2018-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutrition_grade_uk',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='serving_size',
            new_name='nutrition_grades',
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_100g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_100g',
            field=models.IntegerField(null=True),
        ),
    ]
